name: Deploy wheel to dist

on:
    push:
        branches: [main]

jobs:
    build-deploy-bundle:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"

            - name: Install node dependencies
              run: npm ci

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Build
              run: npm run build

            - name: Checkout dist branch
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git checkout --orphan dist
                  git rm -rf .

            - name: Copy wheel to dist branch
              run: |
                  cp dist/*.whl . || true # Copy the wheel file(s)
                  ln -sf $(ls *.whl | tail -n 1) dev.whl
                  git add *.whl dev.whl
                  git commit -m "Update wheel file" || echo "No changes to commit"
                  git push origin dist --force
